" .vimrc
" by Miika Nissi, https://miikanissi.com, https://github.com/miikanissi
" language specific configs at .vim/ftplugin/<language>.vim
" or .vim/after/syntax/<language>.vim for syntax

" jump between parens with % using built-in macro
runtime macros/matchit.vim

" settings
set t_Co=256                                " use 256 colors
highlight ColorColumn ctermbg=7 guibg=grey  " color column
set colorcolumn=88                          " colorcolumn is 88 chars
set background=light                        " light background
syntax on                                   " syntax highlighting on
filetype plugin indent on                   " indentation on
set encoding=utf-8                          " utf-8 always
set mouse=a                                 " enable mouse functionality
set noeb vb t_vb=                           " no error bells
set backspace=indent,eol,start              " normal backspace functionality
set hidden                                  " hides instead of unloads buffers
set wildmode=longest,list,full              " wild mode settings
set wildmenu                                " tab complete shows all matching files
set nocompatible                            " compatibility vim only
set clipboard=unnamedplus                   " uses system clipboard
set tabstop=4                               " tab stops at 4 spaces
set softtabstop=4                           " tab stops at 4 spaces
set shiftwidth=4                            " default shift
set expandtab                               " default tabs
set smartindent                             " default tabs
set nu rnu                                  " hybrid line numbers
set wrap                                    " no wrap
set ignorecase                              " ignores case in search
set smartcase                               " uses smartcase in search
set noswapfile                              " no swap file
set nobackup                                " no backup file
set undodir=~/.vim/undodir                  " undodir for history
set undofile                                " makes undofile for history in undodir
set incsearch                               " incremental search enabled
set ruler                                   " ruler shows cur pos
set lazyredraw                              " no redraw
set magic                                   " magic for regex
set scrolloff=8                             " shows 8 lines under mouse when moving the file
set matchpairs+=<:>                         " highlights matching brackets, '%' to jump between them
set viminfo='100,<9999,s100                 " only stores info from 100 files at a time, 9999 lot.
set viminfo+=n~/.vim/viminfo                " store viminfo in ~/.vim folder
set showcmd                                 " shows the typed command
set updatetime=300                          " default is 4000
set shortmess+=c                            " no messages to ins completion
set signcolumn=yes                          " always show signcolumns

let mapleader = " "

" navigation
nnoremap <PageUp> :bprevious<CR>
nnoremap <PageDown> :bnext<CR>
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l
nnoremap <C-H> <C-W>h
nnoremap gh 0
nnoremap gl $
nnoremap U <C-R>
