#!/bin/bash

odoo_addons_path="$HOME/Documents/odoo/addons/16"

_odoo-docker() {
	local cur prev split
	_init_completion -s -n : || return

	case $prev in
	-u)
		compopt +o nospace
		if [ ! -e "$odoo_addons_path" ]; then
			return
		fi
		odoo_modules="$(find "$odoo_addons_path" -name '__manifest__.py' -printf '%h\n' | rev | cut -d/ -f1 | rev | sort -u)"
		mapfile -t COMPREPLY < <(compgen -W "$odoo_modules" -- "$cur")
		return
		;;
	-V)
		compopt +o nospace
		odoo_addons_path="$HOME/Documents/odoo/addons/$cur"
		mapfile -t COMPREPLY < <(compgen -W "12 13 14 15 16 17" -- "$cur")
		return
		;;
	esac

	$split && return

	_expand || return

	case $cur in
	-*)
		mapfile -t COMPREPLY < <(compgen -W "-h -v -u -V" -- "$cur")
		[[ ${COMPREPLY-} == *= ]] || compopt +o nospace
		;;
	esac
} &&
	complete -F _odoo-docker -o nospace odoo-docker
