#!/bin/bash
# by Miika Nissi, https://miikanissi.com, https://github.com/miikanissi

## Set environment path
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

### BSPC ###
INTERNAL_MONITOR="eDP"
EXTERNAL_MONITOR="HDMI-A-0"
# on first load setup default workspaces
if [[ "$1" = 0 ]]; then
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
		bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
		bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
	else
		bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
	fi
fi
bspc config pointer_modifier mod4
bspc config border_width 5
bspc config window_gap 0
bspc config automatic_scheme longest_side # longest_side, alternate or spiral

bspc config split_ratio 0.52
bspc config top_padding 32
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color "$(xrdb -query | grep color15: | awk '{print $2}')"
bspc config focused_border_color "$(xrdb -query | grep accent: | awk '{print $2}')"

bspc config honor_size_hints true

# BSPWM window rules
# To find out the class and instance of a window, run xprop | grep WM_CLASS
bspc rule -a Gimp state=floating
bspc rule -a Onboard state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Alacritty:Alacritty:ncmpcpp state=floating
bspc rule -a Alacritty:Alacritty:odoo-logs state=floating rectangle=1020x720+0+0 center=on
bspc rule -a Pavucontrol state=floating rectangle=640x480+0+0 center=on
bspc rule -a *:net-runelite-launcher-Launcher state=floating rectangle=1148*754+0+0 layer=above split_dir=north

# AUTOSTART
# Helper function to check for active process, if not found starts program on the background
_run() {
	if ! pgrep -x "${1}" &>/dev/null; then
		"$@" &
	fi
}

# Environment
source ~/.bashrc
xrdb .Xresources &
# Fixes Java applications
wmname LG3D
# Use qt5ct to set Qt theme
export QT_QPA_PLATFORMTHEME="qt5ct"
# for bitwarden
keyctl link @u @s
# Turn on notifications
_run dunst --config ~/.config/dunst/dunstrc

# Keyboard, mouse, cursor, fonts
~/.local/bin/keyboard.sh &
xsetroot -cursor_name left_ptr &
fc-cache -fv &
_run sxhkd -m -1 >> ~/.local/share/sxhkd.log 2>&1

# File browser daemon (automatic mounting etc)
_run pcmanfm -d

# Music daemon
_run mpd

# Network Manager applet
_run nm-applet

# Battery monitoring
~/.local/bin/battery_notifier.sh &

# Set floating desktop
~/.local/bin/bspwm_floating.sh &

# Signal messenger
_run signal-desktop --start-in-tray --use-tray-icon

# Lock screen
_run light-locker --lock-on-suspend --lock-after-screensaver=30

# Wallpaper
~/.local/bin/setbg.sh &

# Redshift to dim screen temperature
_run redshift

# Compositor
# disabled due to freezing issues and unnecessary battery drain
# _run picom --config .config/picom/picom.conf --vsync

# Setup monitors, polybar and wallpaper
~/.local/bin/bspwm_setup_monitors.sh &
