#!/bin/bash
# by Miika Nissi, https://miikanissi.com, https://github.com/miikanissi

### BSPC ###
bspc config pointer_modifier        mod4
bspc config border_width            2
bspc config window_gap              4
bspc config automatic_scheme        longest_side # longest_side, alternate or spiral

bspc config split_ratio             0.52
bspc config top_padding             32
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config focus_follows_pointer   true

bspc config focused_border_color    "#c85e7c"

# BSPWM window rules
bspc rule -a URxvt:ncmpcpp desktop='^5' state=floating follow=on
bspc rule -a Gimp state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

# BSPWM monitors
~/.local/bin/bspwm_setup_monitors.sh &

# AUTOSTART
~/.local/bin/bspwm_autostart.sh &
