#!/bin/sh
# by Miika Nissi, https://miikanissi.com, https://github.com/miikanissi

# make sure all processes are killed
killall -q compton
killall -q polybar
killall -q sxhkd

# wait until the processes have been shut down (just in case)
while pgrep -u $UID -x compton >/dev/null; do sleep 1; done
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done

### AUTOSTART ###
if [[-z which picom ]]; then
  picom --config .config/picom/picom.conf &
else
  compton --config .config/picom/picom.conf &
fi

mpd &
polybar top &
sxhkd &
dunst --config ~/.config/dunst/dunstrc &
xrdb .Xresources & # refresh Xresources
.local/bin/setbg.sh & # sets wallpaper
.local/bin/monitor.sh & # xrandr to set monitors
.local/bin/keyboard.sh # set keyboard conf
# xrandr --output HDMI-1 --same-as eDP-1

### BSPC ###
bspc monitor -d 1 2 3 4 5

bspc config pointer_modifier        mod4
bspc config border_width            2
bspc config window_gap              6
bspc config automatic_scheme        longest_side # longest_side, alternate or spiral

bspc config split_ratio             0.52
bspc config top_padding             32
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config focus_follows_pointer   true

bspc config focused_border_color    "#c85e7c"

bspc rule -a URxvt:ncmpcpp desktop='^5' state=floating follow=on
bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

xsetroot -cursor-name left_ptr &
